name: Docker compose CI on linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: use docker-compose
      run: cd ./example && sh gen-config-yaml.sh && docker-compose -p docker-apisix up -d
